name: phglider
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas==1.2.3
  - erddapy==0.9.0
  - cartopy==0.18.0
  - netcdf4==1.5.6
  - pip==21.0.1
  - cmocean==2.0
  - numpy==1.20.1
  - xarray==0.17.0
  - scikit-learn==0.24.1
  - pip:
    - pyco2sys==1.6.0
