name: phglider
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.7
  - numpy==1.20.1
  - netcdf4==1.5.6
  - pandas==1.2.3
  - xarray==0.16.2
  - cartopy==0.18.0
  - cmocean==2.0
  - erddapy==0.9.0
  - pip==21.0.1
  - pip:
    - pyco2sys==1.6.0

