name: phglider
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas==1.5.0
  - erddapy==1.2.1
  - cartopy==0.21.0
  - netcdf4==1.6.1
  - pip==22.2.2
  - dask==2022.9.1
  - cmocean==2.0
  - numpy==1.23.3
  - xarray==0.19.0
  - scikit-learn==1.1.2
  - geographiclib==2.0
  - ioos_qc==2.0.1
  - gsw==3.6.16
  - pip:
    - pyco2sys==1.8.1
    - seawater==3.3.4
