ph_total:
    qartod:
        gross_range_test:
            suspect_span: [6.5, 9]
            fail_span: [0, 14]
ph_total_shifted:
    qartod:
        gross_range_test:
            suspect_span: [6.5, 9]
            fail_span: [0, 14]
chlorophyll_a:
    qartod:
        gross_range_test:
            fail_span: [0, 50]
sci_flntu_chlor_units:
    qartod:
        gross_range_test:
            fail_span: [0, 50]
